Georgeudev 4
zhenikaKi/Easy-Graphics pull request #16
Opened 2021-12-23 10:30 UTC by GeorgeUG02

сделал сохранение данных в БД на экране с описанием графика и переход на экран с таблицей оттуда

2021-12-23 12:45 UTC, zhenikaKi requested changes

2021-12-23 12:45 UTC, zhenikaKi commented on app/src/main/java/ru/easygraphics/chartsettingsWindow/ChartDescriptionFragment.kt
> +                    chart_id=db.chartDao().getCharts()[db.chartDao().getCharts().size-1].chartId!!
Я упустил один момент. Давай в ru.easygraphics.data.db.dao.ChartDao сделаем небольшие правки. С
```kotlin
suspend fun save(chart: Chart)
```
поменяем на
```kotlin
suspend fun save(chart: Chart): Long
```

И тогда `chart_id` (надо кстати переименовать в `chartId`) можно так получить:
```kotin
chartId = db.chartDao().save( ... )
```

2021-12-23 12:45 UTC, zhenikaKi commented on app/src/main/java/ru/easygraphics/chartsettingsWindow/ChartDescriptionFragment.kt
> +                        db.chartLineDao().delete(cl[i])
А вот удалять линии не стоит. К их id привязаны значения по Y. Они тоже автоматом удаляться. Т.е. после сохранения редактирования графика мы потеряем ВСЕ значения по Y на всех линиях графика.
Тут нужно более строже делать. Получать список сохраненных линий на графике и сравнивать с параметрами редактируемых линий. Если линия удалена, до таким методом ее одну удаляем из базы. А если поменялось название или цвет, то в базе обновлять линию. Ну и ничего в базе не делать, когда линия не изменена.

2021-12-23 12:45 UTC, zhenikaKi commented on app/src/main/java/ru/easygraphics/chartsettingsWindow/ChartDescriptionFragment.kt
> +        fun newInstance(chart_id: Long): Fragment {
Все же тут предлагаю сделать null параметр.
Задать параметр можно так:
```kotlin
fun newInstance(chartId: Long?): Fragment = ChartDescriptionFragment()
  .also {
    chartId?.let { id -> it.arguments = bundleOf(DB.CHART_ID to id) }
  }
```

Саму переменную можно проинициализировать сразу:
```kotlin
private val chartId by lazy { arguments?.getLong(DB.CHART_ID) }
```
Затем ниже можно будет удалить:
```kotlin
var chart_id = requireArguments().getLong(DB.CHART_ID)
```
Потом ниже не придется делать доп.проверку, а сразу сохранять:
```kotlin
chartId = db.chartDao().save( Chart(chartId, ... ) )
```
И после этого делать логику с линиями. Т.е. вместо 
```kotlin
if (... ) { db.chartDao().save... } else { db.chartDao().save ... }
```
будет просто одно сохранение `chartId = db.chartDao().save( Chart(chartId, ... ) )`. При чем ,если графика не было (chartId == null), то он добавится, а если был, то изменится

2021-12-23 16:20 UTC, zhenikaKi requested changes

2021-12-23 16:20 UTC, zhenikaKi commented on app/src/main/java/ru/easygraphics/data/db/repositories/LocalDbRepository.kt
> +        coroutineScope.launch{
В репозитории не нужно оборачивать код в корутины. Метод `saveChartDescription` объявлен как `suspend`. Это означает, что данный метод можно вызвать только внутри корутин, т.е. то место, которое вызывает сохранение (ChartDescriptionViewModel) вызывает его из корутин.

2021-12-23 16:20 UTC, zhenikaKi commented on app/src/main/java/ru/easygraphics/data/db/repositories/LocalDbRepository.kt
> +                    if (i>=cl.size) {
Допустим такой кейс. Есть график ,у него три линии (1, 2, 3). Открываем график на редактирование, удаляем вторую линию. Добавляем новую четвертую. (1, 3, 4). Сейчас удаление не реализовано, но в любом случае будет реализовано. В итоге, даже если не поменяется структура полей ввода по линии
```kotlin
private var list: ArrayList<Pair<EditText, View>> = arrayListOf()
````
И будет реализовано удаление из этого списка просто методом remove, то данное условие `if (i>=cl.size)` выдаст false. Код зайдет в ветку else. И там произойдет магия. Линия 1 сохранится под своим `cl[i].lineId`, далее третья линия сохранится под id второй линии. Т.е. у второй линии будет цвет и название третьей линии. А четвертая линия (новая) сохранится на id третьей линии. 
В итоге у третьей линии грубо говоря будет id второй и все значения, которые раньше были на второй (удалили ее) линии, неожиданно перекинутся на третью линию. А на четвертой линии, хоть она и новая, данные буду от старой третьей линии. В массиве линий `list: ArrayList<Pair<EditText, View>>` изменится порядок линий, а база об этой не знает.

2021-12-23 16:20 UTC, zhenikaKi commented on app/src/main/java/ru/easygraphics/chartsettingsWindow/ChartDescriptionFragment.kt
> +                binding.numberOfDigitsAfterDecimalPoint.toString().toInt(),
Тут упадет ошибка:

> java.lang.NumberFormatException: For input string: "androidx.appcompat.widget.AppCompatEditText{cb2db42 VFED..CL. ........ 0,558-1038,676 #7f09013c app:id/number_of_digits_after_decimal_point aid=1073741827}"

Проблема в том, что объект editText преобразовывается в строку "androidx.appcompat.widget.AppCompatEditText{cb2db42 VFED..CL. ........ 0,558-1038,676 #7f09013c app:id/number_of_digits_after_decimal_point aid=1073741827}" и конвертируется в число.
Нужно делать так:
```kotlin
binding.numberOfDigitsAfterDecimalPoint.text.toString().toInt()
```

Аналогично нужно переделать на всех текстовых полях. Например выше
```kotlin
binding.chartName.toString()
```

2021-12-27 14:39 UTC, gek-m approved these changes

2021-12-27 15:15 UTC, zhenikaKi approved these changes

2021-12-27 15:15 UTC, merged