Georgeudev 5
zhenikaKi/Easy-Graphics pull request #23
Opened 2021-12-28 12:11 UTC by GeorgeUG02

2021-12-28 13:02 UTC, gek-m commented on app/src/main/java/ru/easygraphics/mainWindow/ChartsListAdapter.kt
> +    }
Ругали нас, да и в любом другом языке, переменные p0, p1 и v не читабельны

2021-12-28 13:03 UTC, gek-m commented on app/src/main/java/ru/easygraphics/mainWindow/ChartsListAdapter.kt
> +            }
тоде смаое lcl и так далее, реально тяжко понять

2021-12-28 13:11 UTC, gek-m commented on app/src/main/java/ru/easygraphics/data/db/repositories/DataRepository.kt
> +
list_y_lines -> точно не надо так называть переменные только в хмле, тогд алибо так listYLines, ф лучше yLines (то что это линиии и указывает то что это лист/массив)

2021-12-28 13:14 UTC, gek-m commented on app/src/main/java/ru/easygraphics/data/db/repositories/LocalDbRepository.kt
> +                    )
как раз на вчерашнем уроке преподователь говорил, о таких случаях, типо разбивать на отдельные методы (для читабельности, называть их чтоб понимать что делает), и старониться условия в условиях и т.д.

2021-12-28 13:23 UTC, zhenikaKi requested changes

2021-12-28 13:23 UTC, zhenikaKi commented on app/src/main/java/ru/easygraphics/data/db/repositories/DataRepository.kt
> +    suspend fun getChartsList():List<Pair<Long,String>>
Выше комментарий от другого метода, а не от данного нового. Этот и ниже метод нужно перенести в конец файла

2021-12-28 13:23 UTC, zhenikaKi commented on app/src/main/java/ru/easygraphics/data/db/repositories/LocalDbRepository.kt
> +       db.chartDao().delete(db.chartDao().getChart(chartId))
Нет смысла делать дополнительный запрос в базу на поиск графика, чтобы потом его удалить. Нужно в `ChartDao` добавить:
```kotlin
//удалить график по его id
@Query("delete from ${DB.TABLE_CHARTS} where ${DB.CHART_ID} = :chartId")
suspend fun delete(chartId: Long)
```
И потом вызывать так:
```kotlin
db.chartDao().delete(chartId)
```

2021-12-28 13:23 UTC, zhenikaKi commented on app/src/main/java/ru/easygraphics/mainWindow/ChartsListFragment.kt
> +            view.showContextMenu(10f,10f)
10f - вынести в константу. Можно приватную в данном классе
```kotlin
companion object {
    const val ...
}
```

2021-12-28 13:23 UTC, zhenikaKi commented on app/src/main/res/layout/fragment_charts_list.xml
>      <!--<androidx.recyclerview.widget.RecyclerView
Убрать этот закомментированный код, раз вместо него добавлен другой RecyclerView

2021-12-29 03:56 UTC, zhenikaKi approved these changes

2021-12-29 07:42 UTC, gek-m approved these changes

2021-12-29 07:42 UTC, merged