Georgeudev 2
zhenikaKi/Easy-Graphics pull request #8
Opened 2021-12-17 11:17 UTC by GeorgeUG02

Добавил экран с описанием графика 
Все ошибки исправлены

2021-12-17 12:31 UTC, zhenikaKi requested changes

2021-12-17 12:31 UTC, zhenikaKi commented on app/build.gradle.kts
> +    implementation("com.pes.materialcolorpicker:library:1.2.5")
Давай придерживаться порядка. Номер версии вынести в константы `buildSrc > src > main > java > Dependecies#Version`

2021-12-17 12:31 UTC, zhenikaKi commented on app/src/main/res/layout/fragment_chart_description.xml
> +        </LinearLayout>
Сделать форматирование ctrl+alt+l. А то разметка уехала, не удобно смотреть

2021-12-17 12:34 UTC, zhenikaKi commented on app/src/main/res/layout/fragment_chart_description.xml
> +<?xml version="1.0" encoding="utf-8"?>
Идея норм. На первое время сделать самый минимальный функционал заполнения данных. Потом переделаем на более красивое оформление

2021-12-17 12:59 UTC, zhenikaKi commented on app/src/main/res/layout/fragment_chart_description.xml
> +        </LinearLayout>
Отформатируй еще код пожалуйста. Эти два закрывающихся тега явно не должны быть на одном уровне

2021-12-17 13:05 UTC, gek-m commented on app/src/main/res/layout/fragment_chart_description.xml
> +        </LinearLayout>
30dp -> в переменные ещё добавить чтоб сразу порядок был бы

2021-12-17 13:38 UTC, GeorgeUG02 commented on app/src/main/res/layout/fragment_chart_description.xml
> +        </LinearLayout>
у меня форматирование не сработало на клавиатуре , сделал мышкой через меню, сейчас должно быть все норм

2021-12-17 20:46 UTC, gek-m approved these changes

2021-12-18 03:30 UTC, zhenikaKi approved these changes

2021-12-18 08:54 UTC, merged